services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: playground
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7
    # allkeys : 모든 키, volatile : TTL 설정 키
    # lru : 가장 오래된거 삭제, lfu : 가장 조회안된거 삭제
    command: redis-server --maxmemory 128mb --maxmemory-policy allkeys-lru
    ports:
      - "6379:6379"

volumes:
  mysql-data:
